http:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  postgres:
    host: 'postgres'
    port: '5432'
    db_name: 'test'
    username: 'postgres'
    password: 'postgres'
    migration_path: 'migrations/pg'
    migration_version: 1
  redis:
    host: 'redis'
    port: '6379'
    db_name: 0

nats:
  host: "nats"
  topic: "clickhouse"