nats:
  host: "nats"
  topic: "clickhouse"
  batch_size: 2

clickhouse:
  host: 'clickhouse'
  port: '9000'
  db_name: 'test'
  username: 'clickhouse'
  password: 'clickhouse'
  migration_path: 'migrations/000001_init.up.sql'